### ISSUE TITLE
Documentation code blocks update

### ISSUE THREAD

**Issue by mertssmnoglu** [ismailcankaratas/dbcopycat#7]
# Documentation code blocks update

Hi @ismailcankaratas 

On the website documentation all methods styled with bash code block. In my opinionb changing them with js may give us more meaningful and colorful guide.

**Comment by mertssmnoglu** [comment]
I'm also opened it's pull request ( #8 ). I'll be so happy if you could check it.

**Comment by ismailcankaratas** [comment]
@mertssmnoglu You're right, I merged. Thank you so much
